Use cassandra as database
femiwiki/docker-restbase pull request #2
Opened 2019-02-09 08:10 UTC by lens0021

- 기존에 데이터베이스 설정이 기본값(SQLite)이었던 것을 카산드라로 바꾸고 미디어위키 서버와 통신하도록 변경
- secret.php을 볼륨으로 불러오게 하여 카산드라 접속에 필요한 민감 정보들을 사용함
- 도커파일 일부가 길어져 run 스크립트로 분리

#### 관련 이슈

- https://github.com/femiwiki/femiwiki/issues/52

2019-02-12 12:22 UTC, simnalamburt approved these changes
그 외엔 LGTM. `#!/usr/bin/env node` 만 고치고 바로 머지해쥬세요

2019-02-12 12:22 UTC, simnalamburt commented on run
> +#!/usr/local/bin/node
`#!/usr/bin/env node` 로 수정해주세요

2019-02-13 02:04 UTC, simnalamburt approved these changes
LGTM

2019-02-13 06:23 UTC, simnalamburt requested changes
리뷰 취소. 제가 요청드린거 수정해주세요

2019-02-13 06:23 UTC, simnalamburt commented on run
> +  if (err) throw err;
linter를 안붙였기때문에 할말은 없는데, 웬만하면 한줄짜리 if문에 중괄호 생략라지마세요. `if (err) { throw err; }` 이렇게해주세요. 중괄호생략때문에 실수해서 생기는 버그 많아요 https://www.imperialviolet.org/2014/02/22/applebug.html

2019-02-13 06:23 UTC, simnalamburt commented on run
> +    fs.writeFile(configFile, data, (err) => {
`(err) => ...` 는 `err => ...`로 바꿔주세요

2019-02-13 06:23 UTC, simnalamburt commented on run
> +fs.readFile('/a/secret.php', 'utf8', (err, data) => {
callback 쓰지말고 async/await으로 짭시다 

https://nodejs.org/api/fs.html#fs_fspromises_readfile_path_options

```js
const fs = require('fs').promises;
const data = await fs.readFile('/a/secret.php', 'utf8');
```

2019-02-13 06:48 UTC, lens0021 commented on run
> +  if (err) throw err;
[https://github.com/femiwiki/restbase/commit/6586260737baa305ef9fc272aaa346a2d8d35ea5](https://github.com/femiwiki/restbase/commit/6586260737baa305ef9fc272aaa346a2d8d35ea5)로 수정했습니다

2019-02-13 06:48 UTC, lens0021 commented on run
> +    fs.writeFile(configFile, data, (err) => {
[https://github.com/femiwiki/restbase/commit/c079acc012b813f49f8c91dbd411967e9f06ebd5](https://github.com/femiwiki/restbase/commit/c079acc012b813f49f8c91dbd411967e9f06ebd5) 로 수정했습니다

2019-02-14 03:43 UTC, merged