Cassandra를 MySQL로 대체
femiwiki/docker-restbase pull request #4
Opened 2019-07-25 13:02 UTC by lens0021

https://github.com/femiwiki/femiwiki/issues/86

TBD

2019-07-25 15:26 UTC, simnalamburt requested changes
`npm link`를 쓰는 대신, npm에 femiwiki org를 만들어서 거기에 restbase-mod-table-mysql을 업로드하는 작업이 선행되어야 합니다

2019-07-25 15:27 UTC, simnalamburt commented on Dockerfile
> +RUN apk add --no-cache curl git
git 설치 시점이 당겨진 이유는 뭔가요?

2019-07-25 15:29 UTC, lens0021 commented on Dockerfile
> +RUN apk add --no-cache curl git
rastbase-mod-table-mysql의 npm install을 위해서였는데, npm에 업로드하고 고치면 다시 원래대로 돌릴 듯 합니다

2019-07-25 15:44 UTC, simnalamburt commented
TODO
- [ ] https://github.com/femiwiki/restbase-mod-table-mysql/commit/8eb1ec029a64ecd2547106c1abedf03b7cd250f4 리뷰 필요

2019-07-25 15:48 UTC, simnalamburt commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
전반적으로 github에서 tarball 받는 방식을 버리고, femiwiki/restbase랑 femiwiki/restbase-mod-table-mysql 둘다 npm에 업로드한 뒤 그냥 npm에서 곧바로 다운받아 설치하는 방식으로 바꿔야할거같아요

그리고 npm대신 yarn 쓰면 좋을거같고 yarn.lock 도 커밋해서  reproducible build 구성하면 좋을거같아요

2019-07-26 01:58 UTC, lens0021 commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
> 그냥 npm에서 곧바로 다운받아 설치하는 방식으로 바꿔야할거같아요

위 부분이 잘 모르겠습니다 :cry: 아래와 같이 하면 이상하죠??

```dockerfile
ENV NODE_ENV=production
ARG RESTBASE_VERSION=0.19.3
WORKDIR /a
RUN apk add --no-cache --virtual .build-deps \
    git python make g++
RUN yarn add @femiwiki/restbase@${RESTBASE_VERSION} &&\
    mv node_modules/@femiwiki/restbase /srv/restbase &&\
    mv node_modules/* /srv/restbase/node_modules || exit 0 &&\
    mv yarn.lock /srv/restbase &&\
    rm -rf /a
RUN apk del .build-deps
```

2019-07-26 03:53 UTC, simnalamburt commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
`npm install @femiwiki/restbase` 이렇게 설치하라는 뜻이었어요

2019-07-27 08:15 UTC, lens0021 commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
```sh
$ npm install @femiwiki/restbase
# 출력 중략
+ @femiwiki/restbase@0.19.3
added 268 packages from 223 contributors and audited 413 packages in 10.397s
found 0 vulnerabilities
$ ls
node_modules  package-lock.json
$ ls node_modules/@femiwiki/restbase/
config.example.wikimedia.yaml  debian    lib          package.json  server.js  v1
config.example.yaml            doc       LICENSE      projects      sys
config.test.yaml               index.js  maintenance  README.md     test
```
원하는 결과는 `/svr/restbase`에 `server.js`가 위치하는 것인데, 위와 같이 되어서 이후에 옮겼습니다. 이렇게 하는 것을 말씀하는 것이 맞는지 잘 모르겠습니다...

2019-07-28 08:02 UTC, lens0021 commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
아니면 혹시 글로벌 모드로 설치한 뒤에 실행하면 될까요?

2019-07-29 06:14 UTC, simnalamburt commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
글로벌 모드로 설치한 뒤 실행하거나, `~/node_modules/.bin/어쩌구` 이렇게 하시면 돼요

2019-07-29 08:27 UTC, lens0021 commented on Dockerfile
> +RUN apk add --no-cache curl git
Resolved by https://github.com/femiwiki/docker-restbase/pull/4/commits/0b650900ee0cd6924a45a158e3ebcda82f1eadf1

2019-07-29 08:45 UTC, lens0021 commented on Dockerfile
> +ADD https://github.com/femiwiki/restbase/archive/${RESTBASE_VERSION}-mysql.tar.gz /tmp/a.tar.gz
새 커밋을 푸시했습니다.

- 커밋 : https://github.com/femiwiki/docker-restbase/commit/0b650900ee0cd6924a45a158e3ebcda82f1eadf1
- 파일 : https://github.com/femiwiki/docker-restbase/blob/0b6509/Dockerfile

#### 요약

1. 설치를 git-clone이 아닌 yarn([말씀하셨던](https://discordapp.com/channels/314953743185477644/566264019409698817/603978785846591555) 것)으로 하도록 변경하였습니다
2. RESTBase는 기본 위치인 `./node_module/@femiwiki/restbase`에 그대로 안치시키고, `server.js`(RESTBase의 엔트리 포인트)만 심볼릭 링크를 `/srv/restbase/server.js`로 걸었습니다. 이는 굳이 안 걸어도 상관은 없지만 패스 길이를 좀 줄여서 도커파일의 가독성을 올리기 위함입니다.
2. 그 상태로는 RESTBase가 정상적으로 가동되지 않아 환경 변수(`APP_CONFIG_PATH`, `APP_BASE_PATH`)가 추가되었습니다.

2019-09-20 09:58 UTC, lens0021 commented
태스크에 대한 설명입니다.

### Glossary

- **미디어위키([MediaWiki])**: 누구든 편집할 수 있는 위키를 구동하기 위한 위키 엔진으로 위키미디어 파운데이션([Wikimedia Foundation])에 의해 개발되고 있습니다. 미디어위키는 데이터베이스 서버를 필요로 하며 MariaDB, MySQL, PostgreSQL, SQLite를 지원합니다.
- **위키미디어 프로젝트(Wikimedia project)**: 위키미디어 파운데이션에서 직접 운영하는 위키를 말합니다. 예를 들어 위키백과, 위키낱말사전, 위키미디어 공용, 위키데이터, 미디어위키위키, 메타위키 등이 있습니다.
- **시각편집기(VisualEditor)**: 미디어위키는 역사적인 이유로 문서를 작성/편집할 때 사용자가 위키텍스트(마크다운 비슷한 것으로 생각할 수 있습니다)을 사용하는 것을 기본으로 합니다. 그러나 위키미디어 파운데이션도 시대의 변화에 따라 위지위그 편집기인 시각편집기를 개발하였으며, 이 시각편집기는 위지위그를 지원하면서도 위키텍스트를 훼손하거나 지저분하게 만들지 않고 훌륭히 보존합니다.
- **노드 서비스**: 미디어위키는 기본적으로 [PHP]로 되어 있지만 [Node.js]로 작성된 몇 서비스가 있어 이를 필요에 따라 마치 애드온처럼 붙일 수 있습니다. 구체적으로는 미리 준비한 특정 서비스 디렉토리 안에서 `node server.js`와 같은 명령으로 서비스를 실행하고, 노출되는 IP와 포트를 PHP에 알려주면 이후 서로 알아서 협동합니다(일부 복잡한 과정은 생략했습니다). 다만 위키미디어 프로젝트가 아닌 소규모 위키는 Node.js 서비스는 실행하지 않는 것이 일반적입니다([리브레 위키] 등).<p>대표적인 노드 서비스는 예를 들어 다음과 같은 것이 있습니다.</p>
  - **파소이드(Parsoid)**: 미디어위키의 시각편집기는 위키텍스트를 그에 의존적인 몇 정보를 담은 HTML 엘리먼트로 상호 변환하는 작업을 반복적으로 필요로 하며 이는 일반적인 위키텍스트→HTML 파싱과는 다릅니다. 예를 들어 `[[Project:Main Page]]`라는 위키텍스트를 `<a href="/wiki/Project:Main Page">Project:Main Page</a>`라는 HTML로 표현하면 이 둘은 이론적으로 상호 변환할 수 있겠지만, `{{PAGENAME}}`와 같은 위키텍스트는 최종 HTML에서는 해당 문서의 이름으로 변환되며(예를 들어 `<span>Sub Page</span>`) 이 문자열은 시각편집기에게는 불충분한 정보로 시각편집기로서는 `{{PAGENAME}}`라는 문법과 결과물 `<span>Sub Page</span>`를 모두 갖고 있기를 바랍니다. 그렇기 때문에 편집 중 실제 시각편집기가 갖고 있는 HTML은 `<span about="#mwt1" typeof="mw:Transclusion" data-mw='{"parts":[{"template":{"target":{"wt":"PAGENAME","function":"pagename"},"params":{},"i":0}}]}' id="mwAg">Sub Page</span>`과 같은 복잡한 것(이것은 [실제 API 요청](https://www.mediawiki.org/w/api.php?action=visualeditor&format=json&page=Sub%20Page&paction=parsefragment&wikitext=lorem%7B%7BPAGENAME%7D%7Dipsum) 결과물입니다)이 되고, 이는 편집 중에만 쓰이며 편집 결과물에는 저장되지 않습니다. 이런 파싱이 파소이드에서 처리합니다. 다만 이 작업을 굳이 독립된 Node.js 서비스에서 할 하등의 이유가 없으므로 이를 PHP으로 다시 쓴 일명 [Parsoid/PHP] 프로젝트가 2016년에 제안되어 진행중입니다.<p>여하튼 시각편집기는 반복적인 파싱을 필요로 해서인지 캐싱을 지원하다 못해 캐싱이 되지 않을 때에는 일부 기능이 아예 막힙니다. 시각편집기가 사용하는 캐싱은 RESTBase라는 노드 서비스에서 지원합니다.
  - **레스트베이스(RESTBase)**: 레스트베이스는 여러 노드 서비스들을 위한 캐싱 서비스입니다. 레스트베이스가 도와주는 대부분의 노드 서비스가 Rest API 형태를 띄고 있고(Parsoid는 아마 아닙니다), 레스트베이스 그 자체도 Rest API이기 때문에 이름이 레스트베이스인 것 같습니다. 레스트베이스는 아파치 카산드라([Apache Cassandra])를 데이터베이스로 쓰기 위해 만들어진 서비스지만 개발 편의상 [SQLite]도 지원합니다. 구체적으로, 모든 위키미디어 프로젝트 위키들은 카산드라를 쓰고 SQLite는 유닛 테스트 등에서 사용됩니다. 초기 문서 상으로 레스트베이스는 더 다양한 데이터베이스 지원을 계획했지만 아직 공식적으로 진행된 것은 없습니다.
  - *이 아래에 적힌 서비스 설명은 안 읽어도 됩니다*</p>
  - **Citoid**(사이토이드인지 시토이드인지): 위키백과는 나무위키나 기타 보통 사람들이 일상적으로 웹사이트를 인용할 때 URL만을 전달하는 것과 다르게, URL과 함께 웹 사이트의 이름과 작성자, 접속이 가능하단 것을 확인한 날짜 등을 함께 적습니다. 예를 들어 유튜브의 한 동영상을 인용(혹은 참고 문헌으로 사용)한다면, 해당 웹 페이지의 주소, 동영상의 제목, 동영상을 게시한 날짜, 동영상이 주소가 접속이 가능하단 것을 확인한 날짜 등을 같이 적습니다. 이와 같은 작업으로 인해 해당 영상이 삭제되거나, 유튜브가 망해 전혀 접속이 되지 않는 사태가 발생해도 해당 인용이 어떤 것인지를 추측할 수 있지만, 이렇게 각 정보를 채워넣는 작업이 매우 단순하고 있고 귀찮기 때문에 사용자는 이를 자신이 직접 확인해 적는 것 대신 Citoid에게 대신 구해오도록 시킬 수 있습니다.
  - **그래포이드(Graphoid)**: 위키백과는 차트와 같은 그래프들을 표현하기 위해 사용할 수 있도록 [Vega] 문법을 지원하고 있는데, 이 과정 중 자바스크립트가 필요하기 때문에 이를 사용하지 못하는 유저를 위해 그래포이드는 Vega 문법을 토대로 미리 png 파일을 만들어 저장하고 요청이 있을 때 반환합니다.
  - **매소이드(Mathoid)**: 수학식 렌더링 도우미.
- **`restbase-mod-table-cassandra`**: RESTBase가 사용하는 npm 패키지로 RESTBase와 Cassandra를 이어주는 모듈입니다.
- **`restbase-mod-table-sqlite`**: RESTBase가 사용하는 npm 패키지로 RESTBase와 SQLite를 이어주는 모듈입니다.
- **`restbase-mod-table-spec`**: RESTBase와 연결되는 데이터베이스가 구현하여야 하는 스펙들을 적은 npm 패키지입니다. 간단한 유닛 테스트를 포함하고 있습니다. 위 패키지들의 관계는 OOP로 치면 인터페이스-구현과 비슷합니다.

### 페미위키가 당면한 문제점

카산드라는 많은 리소스를 사용하며, 페미위키는 그러한 리소스 사용에 지불할 충분한 자금을 갖고 있지 못하고 또 그렇게 얻어지는 카산드라의 막대한 성능도 아직 필요로 하지 않습니다. 그러나 단기적으로 파소이드(와 시각편집기)를 원활히 사용하기 위하여, 또 장기적으로는 여러 노드 서비스들을 사용하기 위해 레스트베이스는 페미위키에게 반드시 필요한 서비스입니다.

이를 해결하기 위한 방법은 다음을 들 수 있습니다.

1. 여러 단점을 감수하고 SQLite를 쓴다.
2. 리소스 사용을 감수하면서 Cassandra를 최적화해 사용한다.
3. RESTBase가 MySQL을 Backend Storage로 쓸 수 있도록 개변하여 사용한다 - 페미위키는 미디어위키의 데이터베이스를 위해 이미 MySQL을 사용하고 있으므로 별도의 추가 리소스가 필요하지 않습니다.

이 중 3번을 진행한다고 할 때 다음의 변화가 필요하여 진행했거나 할 예정입니다.

- https://github.com/femiwiki/restbase-mod-table-mysql/commit/2c54d03 - `restbase-mod-table-mysql`는 `restbase-mod-table-spec`를 구현하는 RESTBase를 위한 MySQL 모듈이자 npm package입니다. `restbase-mod-table-sqlite`의 SQLite 관련 코드들을 MySQL이 사용되도록 수정한 버전입니다. 유닛 테스트를 모두 통과하였고 미디어위키에서 직접 사용해보는 대략의 테스트에서 문제가 없어 보였으나 두 데이터베이스가 지원하는 데이터형의 차이로 인해 완전히 동일한 동작을 보증할 수는 없습니다.
- https://github.com/femiwiki/restbase/commit/c560f54 - RESTBase의 `package.json`에 의존성으로 `restbase-mod-table-mysql`를 추가하고, 해당 모듈을 선택할 수 있도록 변경하였습니다.
- https://github.com/femiwiki/docker-restbase/pull/4 - 미디어위키의 RESTBase는 깃헙의 wikimedia/restbase 혹은 npm에서 배포되고 있지만 페미위키를 위해 개조한 버전은 그렇지 못하므로 도커 빌드 파일에 자잘한 차이가 발생합니다. 또 레스트베이스의 설정 변경 또한 포함합니다.

[php]: https://www.php.net/
[node.js]: https://nodejs.org/
[wikimedia foundation]: https://wikimediafoundation.org/
[mediawiki]: https://www.mediawiki.org/wiki/MediaWiki
[리브레 위키]: https://librewiki.net/
[vega]: https://vega.github.io/vega/
[parsoid/php]: https://www.mediawiki.org/wiki/Parsoid/PHP
[apache cassandra]: http://cassandra.apache.org/
[sqlite]: https://www.sqlite.org/

2020-01-03 13:05 UTC, simnalamburt commented
Close하고 sqlite3버전으로 다시 열까요 ㅎ

2020-01-03 13:06 UTC, lens0021 commented
조아요 닫아버리조머

2020-01-06 06:32 UTC, lens0021 commented
Closed by https://github.com/femiwiki/femiwiki/issues/149

2020-01-06 06:32 UTC, closed without merging